In [96]:
import pandas as pd
import numpy as np

list_of_train = ['number_of_slot','number_of_day','number_of_weekday','number_of_hour']
list_of_target = ['stream1','stream2','stream3','stream4','stream5','bandwidth_available_OTT']

data = pd.read_csv("train_data.csv")

#lst_x = []
#for i in range(len(data)):
 #   lst_x.append([data.number_of_slot[i], data.number_of_day[i], data.number_of_weekday[i], data.number_of_hour[i]])

#lst_y = []
#for i in range(len(data)):
 #   lst_y.append([round(data.stream1[i],6) , round(data.stream2[i], 6), round(data.stream3[i], 6),  round(data.stream4[i], 6), round(data.stream5[i], 6), round(data.bandwidth_available_OTT[i], 6)])

x = data[list_of_train]

y = data[list_of_target]

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

#clf = RandomForestClassifier()

reg = RandomForestRegressor(n_estimators=10, oob_score = 1, n_jobs = -1,random_state =600,max_features = "auto")#, min_samples_leaf = 1200)

#reg = RandomForestRegressor()

x_d = pd.read_csv("test_data.csv")

#lst_test_x = []
#for i in range(len(x_d)):
 #   lst_test_x.append([x_d.number_of_slot[i], x_d.number_of_day[i], x_d.number_of_weekday[i], x_d.number_of_hour[i]])

test_x = x_d[list_of_train]

# fit the model to the training data (learn the coefficients)
reg.fit(x, y)
y_pred = reg.predict(test_x)

new_data = pd.read_csv("train_data_errcalc.csv")

test = []
for i in range(len(new_data)):
    test.append([new_data.stream1[i], new_data.stream2[i], new_data.stream3[i], new_data.stream4[i], new_data.stream5[i], new_data.bandwidth_available_OTT[i]])

print(len(test))
from sklearn import metrics
from sklearn.metrics import roc_auc_score

print('root mean squared error :', np.sqrt(metrics.mean_squared_error(test, y_pred)))

# make predictions on the testing set


#print(len(y_pred))
for i in range(len(y_pred)):
    print(y_pred[i])

/Users/wonyoungchoi/anaconda3/envs/Tensorflower/lib/python3.6/site-packages/sklearn/ensemble/forest.py:732: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "


2256
root mean squared error : 1.5504301401482072
[0.32526126 0.16517266 1.79176875 0.65312087 6.35452523 4.76359543]
[0.28557372 0.45806235 2.14238756 0.33747796 5.58532247 6.61345944]
[0.32014797 0.57316536 1.68378086 0.27305545 6.55691552 6.80452004]
[0.83556883 0.77673819 3.32942806 0.19968935 2.96877835 7.33563351]
[0.9450645  0.63122028 2.66788933 0.10580329 3.6450423  7.07035669]
[0.47988327 0.55843109 5.31623119 0.14757047 5.44354897 6.97496816]
[0.28770131 0.68684288 2.74052447 0.99156594 5.89833112 6.35127644]
[0.28610096 0.42124711 0.7879112  0.8291791  5.76503346 5.47532037]
[0.58802156 0.761238   0.63877021 0.60933912 3.41862397 3.62944077]
[0.65424396 1.85362853 0.37813984 0.84359271 1.73175094 2.83127947]
[0.40903069 0.53266422 0.6314446  0.48420058 2.70736616 1.84451315]
[0.53765399 0.58629494 0.97034658 0.4123899  2.20473303 1.35273195]
[0.71433831 1.11968732 0.1855363  0.09220006 1.31818215 0.73828694]
[0.69143523 1.42674881 0.60381943 0.2299524  1.48968681 0.5758455 

[0.         0.69891602 1.39315356 0.12270699 4.18353239 7.22117866]
[0.         0.52648199 1.37620786 0.22068072 3.81137151 7.13772147]
[0.         0.65966398 0.80872624 0.64716353 7.07840585 6.29578644]
[0.         0.38268868 0.63957866 0.62563055 5.10729758 5.75722792]
[0.         0.83648175 0.5744771  0.56930323 4.59820041 3.61722593]
[0.         1.68202808 0.28077299 0.66585177 1.76865111 2.65419781]
[0.         0.48528547 0.12388208 0.36706027 2.82647237 1.85757621]
[0.         0.575579   0.68540601 0.30414106 1.80827723 1.35407682]
[0.         1.10326404 0.12020394 0.11370423 1.44439653 0.7901612 ]
[0.         1.17977507 0.18957999 0.15116061 1.38611135 0.55594406]
[0.         1.6454909  0.43635387 0.13544539 0.69870441 0.96206437]
[0.         1.13475171 0.91886662 0.14424489 1.45944659 0.97594155]
[0.         0.91624506 1.29459266 0.28984432 1.23667986 0.44119048]
[0.         1.01956838 1.13648924 0.43259148 4.8082473  0.03821559]
[0.         1.33432342 0.71990259 0.47085909 2.0

[0.         1.13475171 0.91886662 0.14424489 1.45944659 0.97594155]
[0.         0.91624506 1.29459266 0.28984432 1.23667986 0.44119048]
[0.         1.01956838 1.13648924 0.43259148 4.8082473  0.03821559]
[0.         1.33432342 0.71990259 0.47085909 2.05499163 0.03714292]
[0.         1.08367301 2.03434476 0.7713744  4.23373343 0.47445502]
[0.         0.66666689 2.36903637 0.90690043 3.34606226 0.72808856]
[0.         0.48748919 2.03852471 0.89304514 4.54919285 0.94377756]
[0.         0.27296057 0.40318686 0.48536717 8.77792282 1.32433264]
[0.         0.1586074  0.77281593 0.57539755 5.24690265 3.00016292]
[0.         0.14001258 2.37046999 0.6140488  0.         5.05956505]
[0.         0.25609033 1.06077478 0.473444   0.         6.3180416 ]
[0.         0.64086186 0.95308994 0.19224275 0.         6.84753614]
[0.         0.827887   1.34306332 0.12880709 0.         7.52614011]
[0.         0.61615875 1.45163752 0.17151543 0.         7.3210903 ]
[0.         0.52108974 1.12635899 0.17282158 0. 

[0.         0.68717306 2.01669392 0.98450923 0.         0.68081651]
[0.         0.36553904 1.79065173 1.15658762 0.         0.87598069]
[0.         0.29005717 0.43210973 0.50557856 0.         1.3792232 ]
[0.         0.17260441 0.7617816  0.54313871 0.         2.91324722]
[0.50142032 0.26717369 1.58174641 0.55980264 2.39437593 4.67973375]
[0.16494933 0.61484046 1.23571905 0.30223514 2.23432595 6.13730001]
[0.34252837 1.19946992 0.32703396 0.07816149 2.86598474 6.26907737]
[0.78188784 1.41362746 1.08664959 0.19537289 1.64336867 7.09089298]
[0.65342862 1.31722686 0.41015355 0.15867346 2.10481044 7.77752841]
[0.48066424 0.85177727 1.94260834 0.09964737 1.83830901 7.17352153]
[0.46618792 1.51522135 1.26002727 1.07106058 3.54363529 5.86342668]
[0.38434372 0.85385245 0.56822636 0.75489263 2.90779315 5.13591188]
[0.66708479 1.42265744 0.38988397 0.36700777 1.92792323 3.57806994]
[0.50813603 3.16630579 0.10939021 0.54301157 0.95789793 2.6032957 ]
[0.38151539 0.91738719 0.24759718 0.40985937 1.3

In [48]:
#calculate optimal channel

import pandas as pd
import numpy as np

data = pd.read_csv("best_estimation_result_new.csv")

lst = []
for i in range(len(data)):
    lst.append([data.stream1[i] , data.stream2[i], data.stream3[i],  data.stream4[i], data.stream5[i]])

print(len(lst))
advertise_earning = [4.2,0.795, 2.4, 1.98, 4.62]

sum_of_stream = np.zeros((2256,1))
for i in range(2256):
    sum_of_stream[i] = data.stream1[i] + data.stream2[i] + data.stream3[i] + data.stream4[i] + data.stream5[i]

unsatisfied_demand = np.zeros((2256,5))

for j in range(5):
    for i in range(2256):
        unsatisfied_demand[i,j] = data.bandwidth_available_OTT[i] - sum_of_stream[i]

for j in range(5):
    for i in range(2256):
        if j == 0:
            unsatisfied_demand[i,j] += data.stream1[i]
        if j == 1:
            unsatisfied_demand[i,j] += data.stream2[i]
        if j == 2:
            unsatisfied_demand[i,j] += data.stream3[i]
        if j == 3:
            unsatisfied_demand[i,j] += data.stream4[i]
        if j == 4:
            unsatisfied_demand[i,j] += data.stream5[i]
            
            
#for i in range(2256):
#    print(unsatisfied_demand[i])

'''
avg_unsatisfied_demand = np.zeros((2256,1))
for i in range(2256):
        avg_unsatisfied_demand[i] = (unsatisfied_demand[i,0] + unsatisfied_demand[i,1] + unsatisfied_demand[i,2] + unsatisfied_demand[i,3] + unsatisfied_demand[i,4] ) / 5
'''  

#first, find maximum unsatisfied demand.
m = np.zeros((2256,1))
max_val = np.zeros((2256,1))
for i in range(2256):
    max_val[i] = -999
for k in range(2256):
    for l in range(5):
        if max_val[k] < unsatisfied_demand[k,l]:
            max_val[k] =  unsatisfied_demand[k,l]
            m[k] = l
#advertise_earning = [4.2,0.795, 2.4, 1.98, 4.62]



for k in range(2256):
    if ((unsatisfied_demand[k,3] >= 0) or (abs((unsatisfied_demand[k,3] - max(unsatisfied_demand[k]))) <=0.5) ):
        m[k] = 3
for k in range(2256):
    if ((unsatisfied_demand[k,2] >= 0) or  (abs((unsatisfied_demand[k,2] - max(unsatisfied_demand[k]))) <=1) ) :
        m[k] = 2
for k in range(2256):
    if ((unsatisfied_demand[k,0] >= 0) or (abs((unsatisfied_demand[k,0] - max(unsatisfied_demand[k]))) <=1.3 ) ) :
        m[k] = 0
for k in range(2256):
    if ((unsatisfied_demand[k,4] >= 0) or (abs((unsatisfied_demand[k,4] - max(unsatisfied_demand[k]))) <=1.6 ) ) :
        m[k] = 4

        

for i in range(len(m)):
    print(m[i]+1)


        

2256
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[2.]
[5.]
[5.]
[5.]
[5.]
[5.]
[3.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[2.]
[5.]
[5.]
[5.]
[2.]
[2.]
[2.]
[5.]
[5.]
[1.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[2.]
[5.]
[5.]
[5.]
[5.]
[2.]
[3.]
[5.]
[5.]
[5.]
[5.]
[3.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]


[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[2.]
[5.]
[5.]
[5.]
[5.]
[5.]
[3.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[2.]
[5.]
[5.]
[5.]
[2.]
[2.]
[2.]
[5.]
[5.]
[1.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[2.]
[5.]
[5.]
[5.]
[5.]
[2.]
[3.]
[5.]
[5.]
[5.]
[5.]
[3.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]
[5.]


In [27]:
# Not used
import pandas as pd
import numpy as np

data = pd.read_csv("best_estimation_result.csv")

lst = []
for i in range(len(data)):
    lst.append([data.stream1[i] , data.stream2[i], data.stream3[i],  data.stream4[i], data.stream5[i]])

print(len(lst))
advertise_earning = [4.2,0.795, 2.4, 1.98, 4.62]

sum_of_stream = np.zeros((2256,1))
for i in range(2256):
    sum_of_stream[i] = data.stream1[i] + data.stream2[i] + data.stream3[i] + data.stream4[i] + data.stream5[i]

unsatisfied_demand = np.zeros((2256,5))
for j in range(5):
    for i in range(2256):
        unsatisfied_demand[i,j] = data.bandwidth_available_OTT[i] - (data.stream1[i] + data.stream2[i] + data.stream3[i] + data.stream4[i] + data.stream5[i])
        if j == 1:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream1[i]
        elif j == 2:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream2[i]
        elif j == 3:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream3[i]
        elif j == 4:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream4[i]
        elif j == 5:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream5[i]
        
        
#for i in range(len(unsatisfied_demand)):
#    print(unsatisfied_demand[i])
'''
avg_unsatisfied_demand = np.zeros((2256,1))
for i in range(2256):
        avg_unsatisfied_demand[i] = (unsatisfied_demand[i,0] + unsatisfied_demand[i,1] + unsatisfied_demand[i,2] + unsatisfied_demand[i,3] + unsatisfied_demand[i,4] ) / 5
'''
#first, find maximum unsatisfied demand.
m = np.zeros((2256,1))
max_val = np.zeros((2256,1))
for k in range(2256):
    for l in range(5):
        if max_val[k] < unsatisfied_demand[k,l]:
            max_val[k] =  unsatisfied_demand[k,l]
            m[k] = l

for k in range(2256):
    if unsatisfied_demand[k,4] >= -0.1:
        m[k] = 4
for k in range(2256):
    if unsatisfied_demand[k,5] >= -0.1 :
        m[k] = 5

        

            
            
'''
comp_result = np.zeros((2256,5))
weight_adv = 0.7
weight_demand = 1
for j in range(5):
    for i in range(2256):
        if unsatisfied_demand[i,j] < avg_unsatisfied_demand[i]:
            comp_result[i,j] = ( weight_demand * unsatisfied_demand[i,j] ) + ( weight_adv * advertise_earning[j] )
'''
            
#for i in range(len(comp_result)):
#    print(comp_result[i])


'''
m = np.zeros((2256,1))
max_val = np.zeros((2256,1))
for k in range(2256):
    for l in range(5):
        if max_val[k] < comp_result[k,l]:
            max_val[k] =  comp_result[k,l]
            m[k] = l
'''          
for i in range(len(m)):
    print(m[i]+1)
        




#for i in range(len(new_lst)):
 #       print(new_lst[i])
        
#print(len(new_lst))

2256


IndexError: index 5 is out of bounds for axis 1 with size 5

In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv("best_estimation_result.csv")

lst = []
for i in range(len(data)):
    lst.append([data.stream1[i] , data.stream2[i], data.stream3[i],  data.stream4[i], data.stream5[i]])

print(len(lst))
advertise_earning = [4.2,0.795, 2.4, 1.98, 4.62]

sum_of_stream = np.zeros((2256,1))
for i in range(2256):
    sum_of_stream[i] = data.stream1[i] + data.stream2[i] + data.stream3[i] + data.stream4[i] + data.stream5[i]

unsatisfied_demand = np.zeros((2256,5))
for j in range(5):
    for i in range(2256):
        unsatisfied_demand[i,j] = data.bandwidth_available_OTT[i] - (data.stream1[i] + data.stream2[i] + data.stream3[i] + data.stream4[i] + data.stream5[i])
        if j == 1:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream1[i]
        elif j == 2:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream2[i]
        elif j == 3:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream3[i]
        elif j == 4:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream4[i]
        elif j == 5:
            unsatisfied_demand[i,j] = unsatisfied_demand[i,j] + data.stream5[i]
        
#first, find maximum unsatisfied demand.
m = np.zeros((2256,1))
max_val = np.zeros((2256,1))
for k in range(2256):
    for l in range(5):
        if max_val[k] < unsatisfied_demand[k,l]:
            max_val[k] =  unsatisfied_demand[k,l]
            m[k] = l

for k in range(2256):
    if unsatisfied_demand[k,4] >= -0.1:
        m[k] = 4
for k in range(2256):
    if unsatisfied_demand[k,5] >= -0.1 :
        m[k] = 5
        
        
        
for i in range(len(m)):
    print(m[i]+1)