In [4]:
import pandas as pd
import numpy as np

list_of_train = ['number_of_slot','number_of_day','number_of_weekday','number_of_hour']
list_of_target = ['stream1','stream2','stream3','stream4','stream5','bandwidth_available_OTT']

data = pd.read_csv("train_data.csv")

#lst_x = []
#for i in range(len(data)):
 #   lst_x.append([data.number_of_slot[i], data.number_of_day[i], data.number_of_weekday[i], data.number_of_hour[i]])

#lst_y = []
#for i in range(len(data)):
 #   lst_y.append([round(data.stream1[i],6) , round(data.stream2[i], 6), round(data.stream3[i], 6),  round(data.stream4[i], 6), round(data.stream5[i], 6), round(data.bandwidth_available_OTT[i], 6)])

x = data[list_of_train]

y = data[list_of_target]

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

#clf = RandomForestClassifier()

reg = RandomForestRegressor()

x_d = pd.read_csv("test_data.csv")

#lst_test_x = []
#for i in range(len(x_d)):
 #   lst_test_x.append([x_d.number_of_slot[i], x_d.number_of_day[i], x_d.number_of_weekday[i], x_d.number_of_hour[i]])

test_x = x_d[list_of_train]

# fit the model to the training data (learn the coefficients)
reg.fit(x, y)

# make predictions on the testing set
y_pred = reg.predict(test_x)

print(len(y_pred))
#for i in range(len(y_pred)):
#    print(y_pred[i])

/Users/wonyoungchoi/anaconda3/envs/Tensorflower/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


2256
[0.27983196 0.17052893 1.69578841 0.59700745 6.06696934 4.7519666 ]
[0.27003412 0.45530011 2.33520895 0.36617473 5.54160884 6.57348715]
[0.30535432 0.56731448 2.26259183 0.29908825 6.99263018 6.80514395]
[0.80571377 0.78192419 3.03244441 0.19438041 2.93911046 7.38560828]
[0.94325652 0.60233871 3.06004991 0.09215685 3.94641449 6.80882901]
[0.5318567  0.55850474 5.57614831 0.15221393 4.70830193 6.7817098 ]
[0.32011506 0.76591762 2.93488328 0.87228445 7.01352947 6.24912198]
[0.31796557 0.49824965 1.47858983 0.85155552 6.45825789 5.69674884]
[0.58744167 0.77149771 0.74491074 0.58570691 3.52835963 3.66965083]
[0.64648661 1.8613039  0.37899735 0.81104607 1.70070102 2.78984646]
[0.44841099 0.51898905 0.62797036 0.50675209 3.12083512 1.78796677]
[0.44012878 0.56245323 1.43760254 0.51634858 1.5869197  1.32901246]
[0.72053197 1.11205479 0.24478982 0.10232044 1.29589523 0.73282725]
[0.79082953 1.42085644 0.55561103 0.21843152 1.82446462 0.55807879]
[0.50156847 1.67547206 0.6055719  0.1640362

[0.         0.86389622 2.37505039 0.08102283 4.1467553  6.73258924]
[0.         0.65578009 0.58845935 0.10759407 4.24582799 7.30023683]
[0.         0.50335159 5.38938865 0.21328861 6.73269985 7.02794051]
[0.         0.79956506 1.88808011 0.88477355 8.82588913 5.85949492]
[0.         0.42062327 1.72973061 0.4863838  7.38479407 4.95975085]
[0.         0.84442489 0.75759219 0.7168474  5.56637398 3.82478873]
[0.         1.70487788 0.49356311 0.87401997 2.70289246 2.68288549]
[0.         0.48709564 0.4228956  0.65099618 3.61925081 1.7902449 ]
[0.         0.5803954  1.39710349 0.35595954 2.37192385 1.41715573]
[0.         1.02749281 0.48107593 0.22683313 2.30104871 0.76762097]
[0.         1.32251718 0.79714559 0.18537684 2.69415585 0.56399279]
[0.         2.05053071 1.80831601 0.23641253 0.98305211 0.97953221]
[0.         1.32611634 2.0255781  0.11576883 2.72065174 0.94489206]
[0.         1.00204089 2.90705638 0.2732526  1.63495035 0.42327203]
[0.         1.29532783 2.9311753  0.34775204 6.2

[0.         0.99132174 1.08282386 0.47383672 4.86051668 0.03595874]
[0.         1.3820785  0.9459005  0.42953922 1.80685249 0.03834714]
[0.         1.11483561 1.62913124 0.75897507 4.15894138 0.48184397]
[0.         0.6905288  2.72916517 0.63536766 4.29962266 0.71559732]
[0.         0.45988854 1.88981899 0.92234639 5.74249144 0.88016592]
[ 0.          0.25806928  0.61804453  0.57913037 10.29194503  1.33932002]
[0.         0.15403429 0.89023232 0.52689437 5.45143768 2.93648024]
[0.         0.14282542 2.23502529 0.56759057 0.         5.00501818]
[0.         0.25466296 0.97138769 0.42066118 0.         6.29554128]
[0.         0.63228496 0.95501087 0.1831234  0.         6.77907231]
[0.         0.8370865  1.20073636 0.14406154 0.         7.33601638]
[0.         0.62581841 1.73653212 0.17786559 0.         7.51213709]
[0.         0.5128652  1.4765007  0.19542477 0.         6.70763975]
[0.         0.6420731  0.73189695 0.66442675 0.         6.09537551]
[0.         0.42629392 0.52857304 0.688660

[0.48361117 0.         1.72491507 0.68390175 2.83636702 4.61115089]
[0.17589511 0.         0.96366209 0.54872145 2.5033183  6.3012267 ]
[0.31422798 0.         0.66867435 0.14854735 2.84247858 6.36472525]
[1.06904081 0.         1.46051331 0.18514396 1.54181786 7.67998924]
[0.66292038 0.         1.01189289 0.14982931 1.70343583 7.25595021]
[0.5996541  0.         2.17878388 0.16166392 2.46881743 7.17581962]
[0.49019336 0.         0.71706239 0.90224199 3.03609643 5.6959804 ]
[0.32242663 0.         0.38493096 0.33169044 2.13320902 5.43674178]
[0.67362887 0.         0.38791753 0.59518921 2.30273392 3.7380265 ]
[0.53281393 0.         0.20086321 0.65836823 1.02357471 2.66387599]
[0.26820283 0.         0.40447286 0.61069801 1.60207821 1.76136126]
[0.42393776 0.         0.30959159 0.29579421 0.84424149 1.39578484]
[0.56418449 0.         0.14930801 0.19298875 0.57397861 0.75796146]
[0.73054618 0.         0.30115981 0.15038729 1.12939138 0.57472936]
[0.86664822 0.         0.53801431 0.12828674 0.4

In [13]:
lst = []
for i in range(2256):
            lst.append(max(y_pred[i]))

print(lst)

[6.066969340399999, 6.5734871537, 6.9926301845999985, 7.3856082821, 6.8088290086, 6.781709795200001, 7.013529472200001, 6.4582578876999985, 3.6696508269, 2.789846455, 3.1208351245, 1.5869197013999998, 1.2958952334, 1.8244646173999999, 1.6754720606000002, 3.3150894500999994, 3.4210049513999996, 4.1714027666, 2.5866261750999997, 4.4809451997, 5.642058301899999, 7.366574417299999, 11.519679159, 7.053473186400001, 7.3998683623999995, 8.772883541, 10.3127509011, 6.7325892446, 7.3002368304, 7.0279405069, 8.8258891316, 7.384794073099999, 5.5663739751, 2.7028924554000007, 3.6192508139999995, 2.3719238534, 2.3010487081999997, 2.6941558464, 2.050530713, 2.7206517383, 2.9070563816000003, 6.221154829700001, 2.9237886408, 5.480910734500001, 6.688582330599999, 8.589709329, 11.651924122000002, 6.8768502137, 4.934435279600001, 5.905767741899999, 6.6995734675000005, 7.1900203893, 7.187587312599999, 7.080270617799999, 6.635205630100001, 5.706994240000001, 4.8770931879, 2.568569783, 2.7888124568999997, 1

In [41]:

predstream = np.zeros((2256,5))

for i in range(2256):
    for j in range(5):
        predstream[i,j] =y_pred[i,j] 
        
m = np.zeros((2256,1))
max_val = np.zeros((2256,1))
for k in range(2256):
    for l in range(5):
        if max_val[k] < predstream[k,l]:
            max_val[k] =  predstream[k,l]
            m[k] = l
   
for i in range(len(m)):
    print(m[i])

[4.]
[4.]
[4.]
[2.]
[4.]
[2.]
[4.]
[4.]
[4.]
[1.]
[4.]
[4.]
[4.]
[4.]
[1.]
[2.]
[2.]
[4.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[1.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[1.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[2.]
[2.]
[2.]
[2.]
[2.]
[2.]
[2.]
[3.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[2.]
[2.]
[2.]
[2.]
[2.]
[4.]
[4.]
[4.]
[2.]
[4.]
[2.]
[4.]
[4.]
[4.]
[1.]
[4.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[0.]
[0.]
[2.]
[4.]
[0.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[2.]
[2.]
[2.]
[2.]
[4.]
[4.]
[1.]
[1.]
[4.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[2.]
[2.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[2.]
[4.]
[2.]
[4.]
[4.]
[4.]
[1.]
[4.]
[4.]
[4.]
[4.]
[1.]
[2.]
[2.]
[4.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]


[4.]
[4.]
[4.]
[4.]
[0.]
[0.]
[2.]
[4.]
[0.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[2.]
[2.]
[2.]
[2.]
[4.]
[4.]
[1.]
[1.]
[4.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[2.]
[2.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[2.]
[4.]
[2.]
[4.]
[4.]
[4.]
[1.]
[4.]
[4.]
[4.]
[4.]
[1.]
[2.]
[2.]
[4.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[1.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[1.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[2.]
[2.]
[2.]
[2.]
[2.]
[2.]
[2.]
[3.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[2.]
[2.]
[2.]
[2.]
[2.]
[4.]
[4.]
[4.]
[2.]
[4.]
[2.]
[4.]
[4.]
[4.]
[1.]
[4.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[4.]
[0.]
[0.]
[2.]
[4.]
[0.]
[4.]
[2.]
[4.]
[4.]
[4.]
[4.]
[4.]
[2.]
[2.]
[2.]
[2.]
[4.]
[4.]
[1.]
[1.]
[4.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]


In [30]:
m = max(predstream)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()